version: '3.8'

services:
  redis:
    build:
      context: .
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  web:
    build:
      context: .
    container_name: flask-app
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
