name: Docker Compose Build and Run

on:
  push:
    branches:
      - main
      - master

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Run Docker Compose
        run: |
          docker-compose up --build -d

      - name: Wait for Flask to start
        run: sleep 10

      - name: Run API tests
        run: curl --fail http://localhost:3000/health || exit 1

      - name: Shutdown Docker Compose
        run: docker-compose -f docker-compose.yml down